name: github pages

on:
  pull_request:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install Dependencies
        working-directory: ./mevislab.github.io
        run: npm install
        
      - name: Build
        working-directory: ./mevislab.github.io
        run: hugo --minify --baseURL https://mevislab.github.io/examples/ -d public

      - name: Check HTML
        uses: chabad360/htmlproofer@master
        with:
          directory: "./mevislab.github.io/public"
          arguments: --only-4xx --assume-extension --empty-alt-ignore
        continue-on-error: true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.PUBLISH_TOKEN }}
          publish_dir: ./mevislab.github.io/public
          
          